### ISSUE TITLE
[meta] v0.1 Features

### ISSUE THREAD

**Issue by liamaharon** [liamaharon/cargo-workspace-version-tools#1]
- [x] Fix out of sync crates.io and repo
  - `sync` updates all repo versions to match crates.io

- [x] Make all packages at least stable (no prerelease suffix and at least 0.1.0)
  - `make-at-least-stable`

- [x] Make all packages prerelease (append -alpha.1)
  - `make-prerelease`

- [x] Bump a nightly package, and have all of its dependants bumped correctly to a maximum of stable+1.
  - `bump nightly {patch|minor|major} --package {package} --stable {git-ref}`

- [x] Bump a stable package, and have  all of its dependants bumped correctly. Also if required, create a new branch bumping any nightly packages to keep them the correct # of versions ahead.
  - `bump stable {patch|minor|major} --package {package} --nightly {git-ref}`

- [ ] Clobber `master` into `stable`
  - `clobber` Clobber `master` with stable, stripping `-nightlyYYYYMMDD` suffixes from package versions
